version: '3'
services:
  web:
    image: massdrivercloud/phoenix-chat-example
    # build:
    #   context: .
    environment:
      SECRET_KEY_BASE: oh-so-secr3t
      DATABASE_URL: postgres://postgres:postgres@db:5432/chat?sslmode=disable
      PORT: "4000"
      HOST: chat.example.com
      DATABASE_SSL: false
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    # We use the predefined Postgres image.
    image: postgres:13
    environment:
      # Set user/password for Postgres.
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
